### ISSUE TITLE
RuntimeError and multiple GPU usage

### ISSUE THREAD

**Issue by jmahenriques** [leetemil/thesis_code#1]
Hi @leetemil,

I work with Daniele Granata at Novo Nordisk and I am running some tests on your code because I would like to train the UniRep weights from scratch myself. I am however encountering the following issue:

```
Traceback (most recent call last):
  File "run_unirep.py", line 73, in <module>
    batch_size, batch_train_loss, batch_metrics_dict = train_batch(model, optimizer, xb, args.clip_grad_norm, args.clip_grad_value, scheduler=scheduler, epoch=epoch, batch = batch_idx, num_batches=total_batches)
  File "/z/insulin/users/jheq/software/thesis_code/src/training/training.py", line 95, in train_batch
    loss, batch_metrics_dict = model(xb)
  File "/z/insulin/users/jheq/software/anaconda3/envs/torch-unirep/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/z/insulin/users/jheq/software/thesis_code/src/models/unirep/unirep.py", line 54, in forward
    pred = self.predict(xb, lengths)
  File "/z/insulin/users/jheq/software/thesis_code/src/models/unirep/unirep.py", line 41, in predict
    packed_seq = pack_padded_sequence(embedding, lengths, batch_first = True, enforce_sorted = False)
  File "/z/insulin/users/jheq/software/anaconda3/envs/torch-unirep/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

Have you experienced this issue before? I am able to go around this with `pred = self.predict(xb, lengths.cpu())` but I'm not sure I should be doing this (I don't know what the implications are). 

Also, I am allowing CUDA to see 4 of the 12 GPUs in our in-house machine, and `nvidia-smi` shows that they are all allocated, but only one of the GPUs is effectively doing work. Any comments/suggestions on how to distribute the computation across multiple GPUs?

Thank you,
João

**Comment by jmahenriques** [comment]
BTW, apparently this is the correct "fix" as `nn.utils.rnn.pack_padded_sequence` requires a CPU tensor and `lengths = (xb != self.padding_idx).sum(dim = 1)` returns a GPU tensor with device set to `cuda`.

It's an active bug in PyTorch: https://github.com/pytorch/pytorch/issues/43227

**Comment by jmahenriques** [comment]
Short update, I have changed the code to run UniRep on multiple GPUs by taking inspiration on `run_wavenet_pretrain.py` and it now allocates memory on all GPUs I request, but there are other performance issues. Would be nice if we could have a chat sometime soon, I've sent you an email through my company address.

P.S.: I am also testing the code on your other repo `unirep_project` as that one is already prepared to run on multiple GPUs, but performance issues are also present.
